# Generated by Django 5.2.4 on 2025-08-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competency',
            old_name='mataPelajaran',
            new_name='matapelajaran',
        ),
        migrations.AddField(
            model_name='question',
            name='question_audio',
            field=models.FileField(blank=True, null=True, upload_to='question_audio/'),
        ),
        migrations.AlterUniqueTogether(
            name='competency',
            unique_together={('matapelajaran', 'code')},
        ),
    ]
