# Generated by Django 5.2.4 on 2025-08-23 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_matapelajaran_competency_matapelajaran_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat oleh'),
        ),
    ]
