# Generated by Django 5.2.4 on 2025-08-24 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_exam_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='KomponenNilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_komponen', models.CharField(help_text='Contoh: Tugas Harian, Ulangan Harian, Proyek', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rapor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_uts', models.DecimalField(decimal_places=2, default=0.0, help_text='Nilai Ujian Tengah Semester', max_digits=5)),
                ('nilai_uas', models.DecimalField(decimal_places=2, default=0.0, help_text='Nilai Ujian Akhir Semester', max_digits=5)),
                ('catatan_guru', models.TextField(blank=True, null=True)),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.matapelajaran')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapor_siswa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('siswa', 'mata_pelajaran')},
            },
        ),
        migrations.CreateModel(
            name='Penilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_penilaian', models.CharField(help_text='Contoh: Tugas 1 - Mengerjakan LKS Hal 10', max_length=150)),
                ('nilai', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('komponen', models.ForeignKey(help_text='Jenis penilaian (Tugas, Ulangan, dll.)', on_delete=django.db.models.deletion.PROTECT, to='dashboard.komponennilai')),
                ('rapor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.rapor')),
            ],
        ),
        migrations.DeleteModel(
            name='Nilai',
        ),
    ]
