# Generated by Django 5.2.4 on 2025-08-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_komponennilai_rapor_penilaian_delete_nilai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(verbose_name='Teks Pertanyaan'),
        ),
    ]
