# Generated by Django 5.2.4 on 2025-08-26 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_question_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='tokens',
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='entered_token',
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=8, unique=True)),
                ('is_used', models.BooleanField(default=False, verbose_name='Sudah Digunakan')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Digunakan')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_tokens', to='dashboard.exam')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='examattempt',
            name='token_used',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.token'),
        ),
    ]
