# Generated by Django 5.2.4 on 2025-08-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_exam_tokens_remove_examattempt_entered_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examattempt',
            name='token_used',
        ),
        migrations.AddField(
            model_name='exam',
            name='tokens',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='entered_token',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
