# Generated by Django 5.2.4 on 2025-08-26 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examattempt',
            name='entered_token',
        ),
        migrations.AddField(
            model_name='examattempt',
            name='token_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='dashboard.token'),
        ),
    ]
