# Generated by Django 5.2.4 on 2025-08-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_examattempt_entered_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='current_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
