# Generated by Django 5.2.4 on 2025-08-27 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_examattempt_current_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='tokens',
        ),
        migrations.RemoveField(
            model_name='token',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='token',
            name='used_at',
        ),
        migrations.RemoveField(
            model_name='token',
            name='used_by',
        ),
        migrations.AlterField(
            model_name='token',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='dashboard.exam'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
