# Generated by Django 5.2.4 on 2025-08-27 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_exam_tokens_remove_token_is_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='tokens',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='token',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='token',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='token',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_set', to='dashboard.exam'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
