# Generated by Django 5.2.4 on 2025-08-28 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_exam_tokens_token_is_used_token_used_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='token',
            name='used_at',
        ),
        migrations.RemoveField(
            model_name='token',
            name='used_by',
        ),
    ]
