# Generated by Django 5.2.4 on 2025-08-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_token_is_used_remove_token_used_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='exam_room',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ruang Ujian'),
        ),
    ]
